name: Shepherd

on:
  pull_request:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 17 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Psalm
        env:
          PHPSTAN_ARGS: --show-info=false --stats --output-format=github --shepherd --threads=$(nproc)
        run: make -is psalm
